version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - yolo
      - unet
      - efficientnet

  yolo:
    build: ./yolo
    ports:
      - "8001:8001"

  unet:
    build: ./unet
    ports:
      - "8002:8002"

  efficientnet:
    build: ./efficientnet
    ports:
      - "8003:8003"
